spring.application.name=blogging_app
server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=YmxvZ2dpbmdBcHBTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb25NdXN0QmUyNTZCaXRzTG9uZw==
jwt.expiry=36000000

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha

logging.level.org.springframework.security=debug

spring.profiles.active=dev